<!DOCTYPE html><!-- "' --></script></style></noscript></xmp>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Chyba serveru</title>

<style>
	#error-body { background: white; width: 500px; margin: 70px auto; padding: 10px 20px }
	#error-body h1 { font: bold 47px/1.5 sans-serif; background: none; color: #333; margin: .6em 0 }
	#error-body p { font: 21px/1.5 Georgia,serif; background: none; color: #333; margin: 1.5em 0 }
</style>

<div id="error-body">
	<h1>Chyba serveru</h1>

	<p>
		Omlouváme se, server zaznamenal vnitřní chybu a proto tato stránka nemůže být zobrazena.
		Zkuste to znovu později.<br>
		Pokud bude tento stav přetrvávat déle, kontaktujte <a href="mailto:mail@davidindra.cz">Davida Indru</a>.
	</p>
</div>
